#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor -d 0 1 2 3 4 5

bspc config border_width         2
bspc config window_gap          12
bspc config click_to_focus       true

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Screenkey manage=off

$HOME/.config/polybar/launch.sh
