#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# feh --bg-scale /home/rowan/dotfiles/jameswebb.jpg

# bspc monitor -d I II III IV V VI VII VIII IX X

if [ -f $HOME/.bspwm_monitor_config ]; then
    source $HOME/.bspwm_monitor_config
else
    # bspc monitor -d 1 2 3 4 5 6 7 8
    bspc monitor -d 1 2 3
fi

bspc config border_width         2
bspc config window_gap           0
bspc config click_to_focus       true

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Screenkey manage=off

$HOME/.config/polybar/launch.sh

pgrep -x nm-applet > /dev/null || nm-applet &
pgrep -x pa-applet > /dev/null || pa-applet &
pgrep -x flameshot > /dev/null || flameshot &
pgrep -x blueman-applet > /dev/null || blueman-applet &
pgrep -x light-locker > /dev/null || light-locker --lock-on-lid &

# fix java guis with bspwm
export _JAVA_AWT_WM_NONREPARENTING=1

# feh --bg-scale /home/rowan/dotfiles/jameswebb.jpg
